//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServer.ExecutionPlan.Analysis.SSMSAddin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SqlServer.ExecutionPlan.Analysis.SSMSAddin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception creating new menu item: .
        /// </summary>
        internal static string PlanAnalysis_CreateMenuButton_Exception_creating_new_menu_item {
            get {
                return ResourceManager.GetString("PlanAnalysis_CreateMenuButton_Exception_creating_new_menu_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load SQLEditors assembly..
        /// </summary>
        internal static string PlanAnalysis_PlanAnalysis_Could_not_load_SQLEditors_assembly {
            get {
                return ResourceManager.GetString("PlanAnalysis_PlanAnalysis_Could_not_load_SQLEditors_assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load the ScriptEditorControl type from the SQLEditors assembly..
        /// </summary>
        internal static string PlanAnalysis_PlanAnalysis_Could_not_load_the_ScriptEditorControl_type_from_the_SQLEditors_assembly {
            get {
                return ResourceManager.GetString("PlanAnalysis_PlanAnalysis_Could_not_load_the_ScriptEditorControl_type_from_the_SQ" +
                        "LEditors_assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load the ShowPlanControl type from the SQLEditors assembly..
        /// </summary>
        internal static string PlanAnalysis_PlanAnalysis_Could_not_load_the_ShowPlanControl_type_from_the_SQLEditors_assembly {
            get {
                return ResourceManager.GetString("PlanAnalysis_PlanAnalysis_Could_not_load_the_ShowPlanControl_type_from_the_SQLEdi" +
                        "tors_assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the parent control..
        /// </summary>
        internal static string PlanAnalysis_ShowAnalysis_Could_not_find_the_parent_control {
            get {
                return ResourceManager.GetString("PlanAnalysis_ShowAnalysis_Could_not_find_the_parent_control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception generating plan analysis: .
        /// </summary>
        internal static string PlanAnalysis_ShowAnalysis_Exception_generating_plan_analysis {
            get {
                return ResourceManager.GetString("PlanAnalysis_ShowAnalysis_Exception_generating_plan_analysis", resourceCulture);
            }
        }
    }
}
