//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServer.ExecutionPlan.Analysis.App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SqlServer.ExecutionPlan.Analysis.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue . . ..
        /// </summary>
        internal static string Program_Main_Continue {
            get {
                return ResourceManager.GetString("Program_Main_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the supplied directory: &apos;{0}&apos;..
        /// </summary>
        internal static string Program_Main_Could_not_find_the_supplied_directory____0 {
            get {
                return ResourceManager.GetString("Program_Main_Could_not_find_the_supplied_directory____0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory not found..
        /// </summary>
        internal static string Program_Main_Directory_not_found {
            get {
                return ResourceManager.GetString("Program_Main_Directory_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No execution plan files found at &apos;{0}&apos;..
        /// </summary>
        internal static string Program_Main_No_execution_plan_files_found_at___0 {
            get {
                return ResourceManager.GetString("Program_Main_No_execution_plan_files_found_at___0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the directory that contains the SQL Server execution plans to validate..
        /// </summary>
        internal static string Program_Main_Select_the_directory_that_contains_the_SQL_Server_execution_plans_to_validate {
            get {
                return ResourceManager.GetString("Program_Main_Select_the_directory_that_contains_the_SQL_Server_execution_plans_to" +
                        "_validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: SqlServer.ExecutionPlan.Analysis.App.exe &quot;path to directory containing .sqlplan files&quot;.
        /// </summary>
        internal static string Program_Main_Usage__Tim_Cartwright_Infrastructure_SqlServer_Analysis_App_exe__path_to_directory_containing__sqlplan_files {
            get {
                return ResourceManager.GetString("Program_Main_Usage__Tim Cartwright_Infrastructure_SqlServer_Analysis_App_exe__pat" +
                        "h_to_directory_containing__sqlplan_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///{0} Plan(s) validated in {1} seconds..
        /// </summary>
        internal static string Program_Main_Validated {
            get {
                return ResourceManager.GetString("Program_Main_Validated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validated: {0}.
        /// </summary>
        internal static string Program_Main_Validated_File {
            get {
                return ResourceManager.GetString("Program_Main_Validated_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***Validating plans.
        /// </summary>
        internal static string Program_Main_Validating {
            get {
                return ResourceManager.GetString("Program_Main_Validating", resourceCulture);
            }
        }
    }
}
